# Generated by Django 6.0 on 2026-01-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_product_image_alter_product_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
