# Generated by Django 6.0 on 2026-02-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_collection_options_remove_collection_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
