# Generated by Django 6.0 on 2026-03-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_remove_product_colour_product_color_hex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='collection',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
