# Generated by Django 6.0 on 2026-03-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_collection_status_collection_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='vólke shoppe', max_length=100)),
                ('marquee_text', models.TextField(default='Free shipping on orders over ₹1000 | New arrivals every week | Use code WELCOME10 for 10% off', help_text='Separate multiple messages with |')),
                ('cod_enabled', models.BooleanField(default=True)),
                ('returns_enabled', models.BooleanField(default=True)),
                ('discounts_enabled', models.BooleanField(default=True)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('standard_shipping_cost', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('express_shipping_cost', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
            },
        ),
    ]
