# Generated by Django 6.0 on 2026-03-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_promocode_storesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='returns_enabled',
        ),
        migrations.AddField(
            model_name='promocode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promos/'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
