# Generated by Django 4.2.29 on 2026-03-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_remove_storesettings_returns_enabled_promocode_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
