# Generated by Django 4.2.29 on 2026-03-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_product_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
