# Generated by Django 4.2.29 on 2026-04-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='return_window_days',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
