# Generated by Django 6.0 on 2026-03-05 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_rename_is_active_product_is_available'),
        ('home', '0003_cart_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='adminpanel.product'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'size')},
        ),
    ]
