# Generated by Django 4.2.29 on 2026-03-31 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_orderitem_courier_name_orderitem_inspected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('return', 'Return'), ('exchange', 'Exchange')], default='return', max_length=20)),
                ('reason', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Return Requested'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit to Warehouse'), ('received', 'Received at Warehouse'), ('inspection_passed', 'Inspection Passed'), ('inspection_failed', 'Inspection Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded')], default='requested', max_length=30)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('inspection_notes', models.TextField(blank=True)),
                ('refund_method', models.CharField(blank=True, choices=[('original', 'Original Payment Method'), ('bank', 'Bank Transfer'), ('upi', 'UPI'), ('wallet', 'Store Wallet')], max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_ref', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(related_name='return_requests', to='home.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='home.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
