# Generated by Django 6.0 on 2026-01-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationrequest',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverificationrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
